import type { CommandCatalog } from "../core/model.js";

export const COMPLETION_SHELLS = ["bash", "zsh", "fish", "powershell"] as const;
export type CompletionShell = (typeof COMPLETION_SHELLS)[number];

const TOP_LEVEL = ["list", "doctor", "run", "mcp", "completion"] as const;
const OPTIONS = [
  "--cwd",
  "--workspace",
  "--group",
  "--source",
  "--config",
  "--package-manager",
  "--json",
  "--non-interactive",
  "--dry-run",
  "--yes",
  "--color",
  "--unicode",
  "--no-color",
  "--no-unicode",
  "--help",
  "--version",
] as const;

export function completionCandidates(catalog: CommandCatalog): string[] {
  return [
    ...new Set(
      catalog.commands
        .flatMap((command) => [command.name, ...command.aliases])
        .filter((candidate) => !/[\0\r\n]/u.test(candidate)),
    ),
  ].sort((left, right) => left.localeCompare(right));
}

function bash(): string {
  return `# Generated by runpalette completion bash
_runpalette_completion() {
  local current first candidate
  COMPREPLY=()
  current="\${COMP_WORDS[COMP_CWORD]}"
  first="\${COMP_WORDS[1]-}"

  if [[ "$current" == -* ]]; then
    while IFS= read -r candidate; do
      [[ "$candidate" == "$current"* ]] && COMPREPLY+=("$candidate")
    done <<'RUNPALETTE_OPTIONS'
${OPTIONS.join("\n")}
RUNPALETTE_OPTIONS
  elif (( COMP_CWORD == 1 )); then
    while IFS= read -r candidate; do
      [[ "$candidate" == "$current"* ]] && COMPREPLY+=("$candidate")
    done <<'RUNPALETTE_COMMANDS'
${TOP_LEVEL.join("\n")}
RUNPALETTE_COMMANDS
  elif [[ "$first" == "run" && COMP_CWORD == 2 ]]; then
    while IFS= read -r candidate; do
      [[ "$candidate" == "$current"* ]] && COMPREPLY+=("$candidate")
    done < <(runpalette __complete 2>/dev/null)
  elif [[ "$first" == "completion" && COMP_CWORD == 2 ]]; then
    while IFS= read -r candidate; do
      [[ "$candidate" == "$current"* ]] && COMPREPLY+=("$candidate")
    done <<'RUNPALETTE_SHELLS'
${COMPLETION_SHELLS.join("\n")}
RUNPALETTE_SHELLS
  fi
}
complete -F _runpalette_completion runpalette
`;
}

function zsh(): string {
  return `#compdef runpalette
# Generated by runpalette completion zsh
_runpalette() {
  local candidate
  local -a values
  if (( CURRENT == 2 )); then
    values=(${TOP_LEVEL.map((command) => `'${command}'`).join(" ")})
    _describe 'runpalette command' values
  elif [[ "\${words[2]}" == "run" && CURRENT == 3 ]]; then
    values=("\${(@f)$(runpalette __complete 2>/dev/null)}")
    _describe 'project command' values
  elif [[ "\${words[2]}" == "completion" && CURRENT == 3 ]]; then
    values=(${COMPLETION_SHELLS.map((shell) => `'${shell}'`).join(" ")})
    _describe 'shell' values
  else
    _arguments '*:option:(${OPTIONS.map((option) => `'${option}'`).join(" ")})'
  fi
}
compdef _runpalette runpalette
`;
}

function fish(): string {
  const lines = [
    "# Generated by runpalette completion fish",
    "complete -c runpalette -f",
    ...TOP_LEVEL.map(
      (command) => `complete -c runpalette -n '__fish_use_subcommand' -a '${command}'`,
    ),
    ...OPTIONS.map((option) => {
      const name = option.replace(/^--/u, "");
      return `complete -c runpalette -l '${name}'`;
    }),
    "complete -c runpalette -n '__fish_seen_subcommand_from run' -a '(runpalette __complete 2>/dev/null)'",
    `complete -c runpalette -n '__fish_seen_subcommand_from completion' -a '${COMPLETION_SHELLS.join(" ")}'`,
  ];
  return `${lines.join("\n")}\n`;
}

function powershell(): string {
  return `# Generated by runpalette completion powershell
Register-ArgumentCompleter -Native -CommandName runpalette -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $elements = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })
  $values = @()
  if ($wordToComplete.StartsWith('-')) {
    $values = @(${OPTIONS.map((option) => `'${option}'`).join(", ")})
  } elseif ($elements.Count -le 2) {
    $values = @(${TOP_LEVEL.map((command) => `'${command}'`).join(", ")})
  } elseif ($elements[1] -eq 'run' -and $elements.Count -le 3) {
    $values = @(& runpalette __complete 2>$null)
  } elseif ($elements[1] -eq 'completion' -and $elements.Count -le 3) {
    $values = @(${COMPLETION_SHELLS.map((shell) => `'${shell}'`).join(", ")})
  }
  $values |
    Where-Object { $_ -like "$wordToComplete*" } |
    ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
`;
}

export function generateCompletion(shell: CompletionShell): string {
  if (shell === "bash") return bash();
  if (shell === "zsh") return zsh();
  if (shell === "fish") return fish();
  return powershell();
}
